Repository Collektive/collektive, pull requests merged in 2025-04, with the labels that each got.

#846 docs(dsl): write a minimal documentation for `NeighborsData`
  dsl/src/commonMain/kotlin/it/unibo/collektive/networking/NeighborsData.kt
Labels: documentation, auto-update-merge

#843 fix(compiler-plugin): check the presence of an aggregate context before triggering "loop without align" warnings
  compiler-plugin/src/main/kotlin/it/unibo/collektive/frontend/checkers/NoAlignInsideLoop.kt
Labels: bug, auto-update-rebase

#847 refactor(dsl)!: revisit the core API of Collektive for clarity and coherence
  CHANGELOG.md
  alchemist-incarnation-collektive/src/main/kotlin/it/unibo/alchemist/collektive/device/CollektiveDevice.kt
  alchemist-incarnation-collektive/src/test/resources/it/unibo/collektive/test/kotlin/MyLib.kt
  alchemist-incarnation-collektive/src/test/resources/it/unibo/collektive/test/load-from-kotlin-inline.yml
  compiler-embeddable/src/test/resources/ScriptTest.kt
  compiler-plugin-test/src/test/kotlin/it/unibo/collektive/test/UnnecessaryUseOfConstructsSpec.kt
  compiler-plugin-test/src/test/resources/subjekt/ImproperConstruct.yaml
  compiler-plugin-test/src/test/resources/subjekt/IterationWithAggregate.yaml
  compiler-plugin-test/src/test/resources/subjekt/IterationWithDelegatedAggregate.yaml
  compiler-plugin-test/src/test/resources/subjekt/UnnecessaryUseOfConstructs.yaml
  compiler-plugin-test/src/test/resources/subjekt/UnnecessaryYieldingContext.yaml
  compiler-plugin/src/main/kotlin/it/unibo/collektive/frontend/checkers/UnnecessaryUseOfConstructs.kt
  compiler-plugin/src/main/kotlin/it/unibo/collektive/frontend/checkers/UnnecessaryYielding.kt
  compiler-plugin/src/main/kotlin/it/unibo/collektive/frontend/visitors/ImproperConstructVisitor.kt
  compiler-plugin/src/main/kotlin/it/unibo/collektive/utils/common/AggregateFunctionNames.kt
  dsl/src/commonMain/kotlin/it/unibo/collektive/aggregate/api/Aggregate.kt
  dsl/src/commonMain/kotlin/it/unibo/collektive/aggregate/api/CoreOperators.kt
  dsl/src/commonMain/kotlin/it/unibo/collektive/aggregate/api/Operators.kt
  dsl/src/commonMain/kotlin/it/unibo/collektive/aggregate/api/YieldSupport.kt
  dsl/src/commonMain/kotlin/it/unibo/collektive/aggregate/api/impl/AggregateContext.kt
  dsl/src/commonMain/kotlin/it/unibo/collektive/aggregate/api/operators/AggregateOperators.kt
  dsl/src/commonTest/kotlin/it/unibo/collektive/aggregate/EvolvingTest.kt
  dsl/src/commonTest/kotlin/it/unibo/collektive/aggregate/ExchangeTest.kt
  dsl/src/commonTest/kotlin/it/unibo/collektive/aggregate/NeighboringTest.kt
  dsl/src/commonTest/kotlin/it/unibo/collektive/aggregate/NestedCallsTest.kt
  dsl/src/commonTest/kotlin/it/unibo/collektive/aggregate/SharingTest.kt
  dsl/src/commonTest/kotlin/it/unibo/collektive/alignment/AlignmentTest.kt
  dsl/src/commonTest/kotlin/it/unibo/collektive/alignment/BranchAlignmentTest.kt
  dsl/src/commonTest/kotlin/it/unibo/collektive/branch/IfConditionTest.kt
  dsl/src/commonTest/kotlin/it/unibo/collektive/branch/IfElseBlockTest.kt
  dsl/src/commonTest/kotlin/it/unibo/collektive/branch/IfElseSingleExpressionTest.kt
  dsl/src/commonTest/kotlin/it/unibo/collektive/branch/WhenTest.kt
  dsl/src/commonTest/kotlin/it/unibo/collektive/entrypoint/CollektiveTest.kt
  dsl/src/commonTest/kotlin/it/unibo/collektive/field/FieldManipulationTest.kt
  dsl/src/commonTest/kotlin/it/unibo/collektive/field/FieldOpsTest.kt
  dsl/src/commonTest/kotlin/it/unibo/collektive/field/operations/FieldsTest.kt
  dsl/src/commonTest/kotlin/it/unibo/collektive/networking/SerializationTest.kt
  site/docs/tutorials/dsl-descriptions.mdx
  stdlib/src/commonMain/kotlin/it/unibo/collektive/stdlib/spreading/Gossip.kt
  stdlib/src/commonMain/kotlin/it/unibo/collektive/stdlib/spreading/Spreading.kt
  stdlib/src/commonTest/kotlin/it/unibo/collektive/stdlib/test/DistanceToTest.kt
Labels: core-components

#841 feat(stdlib)!: the best gradient cast you've ever seen
  dsl/src/commonTest/kotlin/it/unibo/collektive/aggregate/ExchangeTest.kt
  dsl/src/commonTest/kotlin/it/unibo/collektive/aggregate/NeighboringTest.kt
  dsl/src/commonTest/kotlin/it/unibo/collektive/aggregate/SharingTest.kt
  dsl/src/commonTest/kotlin/it/unibo/collektive/networking/SerializationTest.kt
  stdlib/build.gradle.kts
  stdlib/src/commonMain/kotlin/it/unibo/collektive/stdlib/spreading/DistanceTo.kt
  stdlib/src/commonMain/kotlin/it/unibo/collektive/stdlib/spreading/GradientCast.kt
  stdlib/src/commonMain/kotlin/it/unibo/collektive/stdlib/spreading/Spreading.kt
  stdlib/src/commonMain/kotlin/it/unibo/collektive/stdlib/util/DistanceMetrics.kt
  stdlib/src/commonTest/kotlin/it/unibo/collektive/stdlib/test/DistanceToTest.kt
  stdlib/src/commonTest/kotlin/it/unibo/collektive/stdlib/test/GossipTest.kt
  stdlib/src/commonTest/kotlin/it/unibo/collektive/stdlib/test/GradientCastTest.kt
  test-tooling/build.gradle.kts
  test-tooling/src/commonMain/kotlin/it/unibo/collektive/testing/Environment.kt
  test-tooling/src/commonMain/kotlin/it/unibo/collektive/testing/EnvironmentWithMeshNetwork.kt
  test-tooling/src/commonMain/kotlin/it/unibo/collektive/testing/Grids.kt
  test-tooling/src/commonMain/kotlin/it/unibo/collektive/testing/Node.kt
  test-tooling/src/commonMain/kotlin/it/unibo/collektive/testing/Position.kt
  test-tooling/src/commonMain/kotlin/it/unibo/collektive/testing/SerializingMailbox.kt
Labels: auto-update-rebase

#850 feat(dsl): generalize `exchanging`
  dsl/src/commonMain/kotlin/it/unibo/collektive/aggregate/api/Aggregate.kt
  dsl/src/commonMain/kotlin/it/unibo/collektive/aggregate/api/CoreOperators.kt
  dsl/src/commonMain/kotlin/it/unibo/collektive/aggregate/api/Operators.kt
  dsl/src/commonMain/kotlin/it/unibo/collektive/aggregate/api/YieldSupport.kt
  dsl/src/commonMain/kotlin/it/unibo/collektive/aggregate/api/impl/AggregateContext.kt
Labels: auto-update-rebase

#854 fix(test-tooling): fix bugged message preparation ignoring `exchange`d messages
  test-tooling/src/commonMain/kotlin/it/unibo/collektive/testing/Node.kt
Labels: auto-update-rebase

#852 feat(dsl): add `collect` and `collectDistinct` to the field reduction operations
  dsl/src/commonMain/kotlin/it/unibo/collektive/field/operations/Fields.kt
Labels: auto-update-rebase

#855 feat(test-tooling): add quick node-access method to `Environment`
  test-tooling/src/commonMain/kotlin/it/unibo/collektive/testing/Environment.kt
Labels: auto-update-rebase

#851 style(dsl): sort `Field` members
  dsl/src/commonMain/kotlin/it/unibo/collektive/field/Field.kt
Labels: auto-update-rebase

#853 fix(dsl): fix bugged management of overrides, with undesired misalignment in case of `exchange`
  dsl/src/commonMain/kotlin/it/unibo/collektive/networking/OutboundEnvelope.kt
Labels: auto-update-rebase

#856 style(stdlib): fix linguistic antipattern
  stdlib/src/commonMain/kotlin/it/unibo/collektive/stdlib/spreading/GradientCast.kt
Labels: auto-update-rebase

#857 fix(stdlib)!: fix hop-distance metric and general metric usage in gradient casts
  stdlib/src/commonMain/kotlin/it/unibo/collektive/stdlib/spreading/DistanceTo.kt
  stdlib/src/commonMain/kotlin/it/unibo/collektive/stdlib/spreading/GradientCast.kt
  stdlib/src/commonMain/kotlin/it/unibo/collektive/stdlib/util/DistanceMetrics.kt
  stdlib/src/commonTest/kotlin/it/unibo/collektive/stdlib/test/DistanceToTest.kt
  stdlib/src/commonTest/kotlin/it/unibo/collektive/stdlib/test/GradientCastTest.kt
Labels: auto-update-rebase

#848 feat(stdlib): implement convergeCast
  dsl/src/commonMain/kotlin/it/unibo/collektive/aggregate/api/Operators.kt
  dsl/src/commonMain/kotlin/it/unibo/collektive/aggregate/api/impl/AggregateContext.kt
  dsl/src/commonMain/kotlin/it/unibo/collektive/field/Field.kt
  gradle/libs.versions.toml
  stdlib/build.gradle.kts
  stdlib/src/commonMain/kotlin/it/unibo/collektive/stdlib/accumulation/ConvergeCast.kt
  stdlib/src/commonMain/kotlin/it/unibo/collektive/stdlib/util/DistanceMetrics.kt
  stdlib/src/commonMain/kotlin/it/unibo/collektive/stdlib/util/Maybe.kt
  stdlib/src/commonTest/kotlin/it/unibo/collektive/stdlib/test/ConvergeCastTest.kt
Labels: auto-update-rebase

#866 fix(alchemist-incarnation-collektive): make the DSL and the stdlib API-level dependencies to simplify the import
  alchemist-incarnation-collektive/build.gradle.kts
Labels: auto-update-rebase

#868 fix(release): force dependencies on the compiler-plugin to use the same version of the project
  alchemist-incarnation-collektive/build.gradle.kts
  build.gradle.kts
  compiler-embeddable/build.gradle.kts
  compiler-plugin-test/build.gradle.kts
  settings.gradle.kts
Labels: auto-update-rebase

#869 fix(alchemist-incarnation-collektive): provide access to the random generator and simplify the API
  alchemist-incarnation-collektive/src/main/kotlin/it/unibo/alchemist/CollektiveIncarnation.kt
  alchemist-incarnation-collektive/src/main/kotlin/it/unibo/alchemist/collektive/CollektiveAlchemistProgram.kt
  alchemist-incarnation-collektive/src/main/kotlin/it/unibo/alchemist/collektive/device/CollektiveDevice.kt
  alchemist-incarnation-collektive/src/main/kotlin/it/unibo/alchemist/collektive/device/DistanceSensor.kt
  alchemist-incarnation-collektive/src/test/kotlin/it/unibo/collektive/test/LoadingWithAlchemistTest.kt
  alchemist-incarnation-collektive/src/test/resources/it/unibo/collektive/test/kotlin/MyLib.kt
  alchemist-incarnation-collektive/src/test/resources/it/unibo/collektive/test/load-from-kotlin-inline.yml
Labels: auto-update-rebase

#875 style(stdlib): prefer the `Accumulator` typealias in `distanceTo`
  stdlib/src/commonMain/kotlin/it/unibo/collektive/stdlib/spreading/DistanceTo.kt
Labels: auto-update-rebase

#876 fix(stdlib): pass a metric `Field` to `bellmanFordGradientCast` instead of a function
  stdlib/src/commonMain/kotlin/it/unibo/collektive/stdlib/spreading/GradientCast.kt
  stdlib/src/commonTest/kotlin/it/unibo/collektive/stdlib/test/GradientCastTest.kt
Labels: auto-update-rebase

#873 fix(stdlib): improve `gradientCast` multi-path multi-source management when the maximum path count is constrained
  stdlib/src/commonMain/kotlin/it/unibo/collektive/stdlib/spreading/GradientCast.kt
  stdlib/src/commonTest/kotlin/it/unibo/collektive/stdlib/test/GradientCastTest.kt
Labels: auto-update-rebase

#879 fix(stdlib): improve and greatly simplify `gradientCast`
  stdlib/src/commonMain/kotlin/it/unibo/collektive/stdlib/spreading/GradientCast.kt
Labels: auto-update-rebase

#886 test(stdlib): add a convergcast test on collections with custom distance metric
  stdlib/src/commonTest/kotlin/it/unibo/collektive/stdlib/test/ConvergeCastTest.kt
Labels: auto-update-rebase

#887 fix(alchemist-incarnation-collektive): fix a bug preventing `exchanging` to work as expected
  alchemist-incarnation-collektive/src/main/kotlin/it/unibo/alchemist/collektive/device/CollektiveDevice.kt
Labels: auto-update-rebase

#885 perf(dsl): minimize the data customization when `exchanging`
  dsl/src/commonMain/kotlin/it/unibo/collektive/aggregate/api/impl/AggregateContext.kt
Labels: auto-update-rebase

#890 perf(dsl): remove useless `toList()` transformation of a `List`
  dsl/src/commonMain/kotlin/it/unibo/collektive/field/Field.kt
Labels: auto-update-rebase

#889 perf(dsl): transform array-backed fields to sequences before mapping
  dsl/src/commonMain/kotlin/it/unibo/collektive/field/Field.kt
Labels: auto-update-rebase

#888 perf(dsl)!: make `Field.neighbors` a `Set`
  dsl/src/commonMain/kotlin/it/unibo/collektive/field/Field.kt
Labels: auto-update-rebase

#891 fix(alchemist-incarnation-collektive): adjust the retention messages and fix internal time
  alchemist-incarnation-collektive/src/main/kotlin/it/unibo/alchemist/collektive/device/CollektiveDevice.kt
Labels: auto-update-rebase

#897 feat: provide better alignment clash errors
  collektive-compiler-plugin/src/main/kotlin/it/unibo/collektive/utils/common/CollektiveIrUtils.kt
  collektive-dsl/src/commonMain/kotlin/it/unibo/collektive/aggregate/AlignmentClashException.kt
  collektive-dsl/src/commonMain/kotlin/it/unibo/collektive/aggregate/api/DataSharingMethod.kt
  collektive-dsl/src/commonMain/kotlin/it/unibo/collektive/networking/OutboundEnvelope.kt
  collektive-dsl/src/commonMain/kotlin/it/unibo/collektive/path/Path.kt
  collektive-dsl/src/commonTest/kotlin/it/unibo/collektive/path/PathTest.kt
Labels: auto-update-rebase

#899 style(dsl): rename `evolv`/`e`/`ing` type arguments
  collektive-dsl/src/commonMain/kotlin/it/unibo/collektive/aggregate/api/impl/AggregateContext.kt
Labels: auto-update-rebase

#898 fix(alchemist-incarnation-collektive): support Boolean properties
  alchemist-incarnation-collektive/src/main/kotlin/it/unibo/alchemist/CollektiveIncarnation.kt
Labels: auto-update-rebase

#900 feat(stdlib): add support for non-Riemann manifolds in `gradientCast` and `distanceTo`
  collektive-dsl/src/commonMain/kotlin/it/unibo/collektive/aggregate/api/impl/AggregateContext.kt
  collektive-stdlib/src/commonMain/kotlin/it/unibo/collektive/stdlib/spreading/DistanceTo.kt
  collektive-stdlib/src/commonMain/kotlin/it/unibo/collektive/stdlib/spreading/GradientCast.kt
Labels: auto-update-rebase, standard-library

#901 feat(dsl): when possible, present the neighbors sorted when stringifying a `Field`
  collektive-dsl/src/commonMain/kotlin/it/unibo/collektive/field/Field.kt
Labels: auto-update-rebase

#907 style(dsl): fix incorrect suppression
  collektive-dsl/src/commonTest/kotlin/it/unibo/collektive/path/PathTest.kt
Labels: auto-update-rebase

#906 build(collektive-gradle-plugin): prefer `assignGitSemanticVersion()` over custom methods
  collektive-gradle-plugin/build.gradle.kts
Labels: auto-update-rebase

#908 test(dsl): fix the network so that it does not send messages to self
  collektive-dsl/src/commonTest/kotlin/it/unibo/collektive/network/NetworkManager.kt
Labels: auto-update-rebase

#913 test(alchemist-incarnation-collektive): throw exception on simulation failure
  alchemist-incarnation-collektive/src/test/kotlin/it/unibo/collektive/test/gradient/GradientTest.kt
Labels: auto-update-rebase

#912 fix(compiler-plugin): fix wording of some warnings
  collektive-compiler-plugin-test/src/test/kotlin/it/unibo/collektive/test/IterationUsingDelegatesWithoutAlign.kt
  collektive-compiler-plugin-test/src/test/kotlin/it/unibo/collektive/test/IterationWithoutAlign.kt
  collektive-compiler-plugin-test/src/test/resources/subjekt/IterationWithAggregate.yaml
  collektive-compiler-plugin-test/src/test/resources/subjekt/IterationWithDelegatedAggregate.yaml
  collektive-compiler-plugin/src/main/kotlin/it/unibo/collektive/frontend/checkers/KtDefaultErrorMessagesCollektive.kt
Labels: auto-update-rebase

#919 docs(website): propose a logo for Collektivize
  site/static/img/collektivize-logo.svg
Labels: auto-update-rebase

#923 fix(collektivize): add plugin project description
  collektivize/build.gradle.kts
Labels: auto-update-rebase

#922 fix(compiler-plugin): fail with error when branching constructs return fields
  collektive-compiler-plugin-test/src/test/kotlin/it/unibo/collektive/test/BranchesCannotReturnFieldTest.kt
  collektive-compiler-plugin-test/src/test/kotlin/it/unibo/collektive/test/util/CompileUtils.kt
  collektive-compiler-plugin-test/src/test/resources/it/unibo/collektive/test/BrokenBranch.kt
  collektive-compiler-plugin/src/main/kotlin/it/unibo/collektive/AlignmentComponentRegistrar.kt
  collektive-compiler-plugin/src/main/kotlin/it/unibo/collektive/frontend/CollektiveExtension.kt
  collektive-compiler-plugin/src/main/kotlin/it/unibo/collektive/frontend/checkers/FirCollektiveErrors.kt
  collektive-compiler-plugin/src/main/kotlin/it/unibo/collektive/frontend/checkers/KtDefaultErrorMessagesCollektive.kt
  collektive-compiler-plugin/src/main/kotlin/it/unibo/collektive/frontend/checkers/WhenReturnsField.kt
  collektive-dsl/src/commonMain/kotlin/it/unibo/collektive/aggregate/api/impl/AggregateContext.kt
Labels: auto-update-rebase

#940 fix(stdlib): fix broken Bellman-Ford gradient
  collektive-stdlib/src/commonMain/kotlin/it/unibo/collektive/stdlib/spreading/GradientCast.kt
Labels: auto-update-rebase

#936 Update README.md Maven Coordinates
  README.md
Labels: auto-update-rebase

#941 style: update copyright header in KotlinPoetUtils.kt
  collektivize/src/main/kotlin/it/unibo/collektive/collektivize/utils/KotlinPoetUtils.kt
Labels: auto-update-rebase

#944 docs(readme): rewrite the readme file
  README.md
Labels: auto-update-merge

#939 build: run the Kotlin compiler in-process to facilitate debugging inside the IDE
  collektive-stdlib/gradle.properties
  gradle.properties
Labels: auto-update-rebase

#942 fix(alchemist-incarnation): fix broken gradient
  alchemist-incarnation-collektive/src/test/resources/it/unibo/collektive/test/kotlin/MyLib.kt
  alchemist-incarnation-collektive/src/test/resources/it/unibo/collektive/test/load-from-kotlin-inline.yml
Labels: auto-update-rebase

#943 style(dsl): sort members in `OutboundEnvelope`
  collektive-dsl/src/commonMain/kotlin/it/unibo/collektive/networking/OutboundEnvelope.kt
Labels: auto-update-rebase
